// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fe
List fe(NumericMatrix threshold, NumericMatrix CC, NumericMatrix CE, NumericMatrix EE, NumericMatrix M3);
RcppExport SEXP _foRgotten_fe(SEXP thresholdSEXP, SEXP CCSEXP, SEXP CESEXP, SEXP EESEXP, SEXP M3SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type CC(CCSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type CE(CESEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type EE(EESEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type M3(M3SEXP);
    rcpp_result_gen = Rcpp::wrap(fe(threshold, CC, CE, EE, M3));
    return rcpp_result_gen;
END_RCPP
}
// fe_left
DataFrame fe_left(NumericMatrix threshold, NumericMatrix CC, NumericMatrix CE, NumericMatrix M3);
RcppExport SEXP _foRgotten_fe_left(SEXP thresholdSEXP, SEXP CCSEXP, SEXP CESEXP, SEXP M3SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type CC(CCSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type CE(CESEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type M3(M3SEXP);
    rcpp_result_gen = Rcpp::wrap(fe_left(threshold, CC, CE, M3));
    return rcpp_result_gen;
END_RCPP
}
// fe_right
DataFrame fe_right(NumericMatrix threshold, NumericMatrix CE, NumericMatrix EE, NumericMatrix M3);
RcppExport SEXP _foRgotten_fe_right(SEXP thresholdSEXP, SEXP CESEXP, SEXP EESEXP, SEXP M3SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type CE(CESEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type EE(EESEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type M3(M3SEXP);
    rcpp_result_gen = Rcpp::wrap(fe_right(threshold, CE, EE, M3));
    return rcpp_result_gen;
END_RCPP
}
// maxmin_rcpp
NumericMatrix maxmin_rcpp(NumericMatrix matrix_1, NumericMatrix matrix_2);
RcppExport SEXP _foRgotten_maxmin_rcpp(SEXP matrix_1SEXP, SEXP matrix_2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type matrix_1(matrix_1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type matrix_2(matrix_2SEXP);
    rcpp_result_gen = Rcpp::wrap(maxmin_rcpp(matrix_1, matrix_2));
    return rcpp_result_gen;
END_RCPP
}
// Rcpp_directEffects
List Rcpp_directEffects(arma::cube& M, CharacterVector rownamesData, CharacterVector colnamesData, double thr, double reps);
RcppExport SEXP _foRgotten_Rcpp_directEffects(SEXP MSEXP, SEXP rownamesDataSEXP, SEXP colnamesDataSEXP, SEXP thrSEXP, SEXP repsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube& >::type M(MSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type rownamesData(rownamesDataSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type colnamesData(colnamesDataSEXP);
    Rcpp::traits::input_parameter< double >::type thr(thrSEXP);
    Rcpp::traits::input_parameter< double >::type reps(repsSEXP);
    rcpp_result_gen = Rcpp::wrap(Rcpp_directEffects(M, rownamesData, colnamesData, thr, reps));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_foRgotten_fe", (DL_FUNC) &_foRgotten_fe, 5},
    {"_foRgotten_fe_left", (DL_FUNC) &_foRgotten_fe_left, 4},
    {"_foRgotten_fe_right", (DL_FUNC) &_foRgotten_fe_right, 4},
    {"_foRgotten_maxmin_rcpp", (DL_FUNC) &_foRgotten_maxmin_rcpp, 2},
    {"_foRgotten_Rcpp_directEffects", (DL_FUNC) &_foRgotten_Rcpp_directEffects, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_foRgotten(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
