# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fe <- function(threshold, CC, CE, EE, M3) {
    .Call(`_foRgotten_fe`, threshold, CC, CE, EE, M3)
}

fe_left <- function(valueOverThreshold, M1, M2, M3) {
    .Call(`_foRgotten_fe_left`, valueOverThreshold, M1, M2, M3)
}

fe_right <- function(valueOverThreshold, M1, M2, M3) {
    .Call(`_foRgotten_fe_right`, valueOverThreshold, M1, M2, M3)
}

#' @useDynLib foRgotten, .registration=TRUE
maxmin_rcpp <- function(matrix_1, matrix_2) {
    .Call(`_foRgotten_maxmin_rcpp`, matrix_1, matrix_2)
}

